image: Visual Studio 2017

matrix:
  fast_finish: true

platform:
  - x86

configuration:
  - Release
  - Debug

clone_folder: c:\projects\libwebrtc

before_build:
  - cmd: set GYP_MSVS_VERSION=2017
  - cd c:\projects\libwebrtc
  - if "%platform%"=="x86" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - if "%platform%"=="x64" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DWEBRTC_BRANCH_HEAD=refs/branch-heads/66 -DBUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=c:\projects\libwebrtc .

build:
  project: PACKAGE.vcxproj

artifacts:
  - path: libwebrtc-*.zip
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: QQrYk1F7DLgQ9eht+J6hvDiDRu8a+AKKwsOetybrL8B32UYxlNJKSZIpD0yHPVsx
  artifact: /libwebrtc-.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

test: off
